### ISSUE TITLE
'[<Fabric.MainViewController 0x788a5400> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key [insert something here].'

### ISSUE THREAD

**Issue by James-Parsons** [NCCA-FBLA/Fabric-iOS#2]
Several of the view controllers are throwing an exception in this format. Specifically, the `MainViewController` and `SignInViewController` are acting up, I am currently looking into this, but if you find a solution, please do commit it.

**Comment by Tyler-Darby** [comment]
Fixed in 4d84404ce2f0b9324808c91b3da37236d58a7e19.
